nodeLinker: node-modules
packageExtensions:
  "@angular-eslint/schematics@*":
    peerDependencies:
      eslint: "*"
      typescript: "*"
  lerna@*:
    peerDependencies:
      nx: "*"
      typescript: "*"
  "@nrwl/devkit@*":
    peerDependencies:      
      typescript: "*"

